# Generated by Django 3.0.5 on 2020-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='losses',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='lp',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='wins',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
