# Generated by Django 3.0.5 on 2020-11-12 12:38

import check.models
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('wait', models.IntegerField()),
                ('summonerName', models.CharField(max_length=50)),
                ('crolling', models.BooleanField(default=False)),
                ('getMatchlist', models.BooleanField(default=False)),
                ('getMatches', models.CharField(max_length=10, null=True, validators=[django.core.validators.int_list_validator])),
                ('createDatas', models.BooleanField(default=False)),
                ('start', djongo.models.fields.ArrayField(model_container=check.models.Start, model_form_class=check.models.StartForm, null=True)),
                ('tier', models.IntegerField(null=True)),
                ('accountId', models.CharField(max_length=100, null=True)),
                ('matches', djongo.models.fields.ArrayField(model_container=check.models.Match, model_form_class=check.models.MatchForm, null=True)),
            ],
        ),
    ]
